# Generated by Django 5.2 on 2025-04-30 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(related_name='polls', through='polls.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='polls.polloption'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='polls.poll'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
